[package]
name = "ralph"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27"
egui-wgpu = "0.27"
egui-winit = "0.27"
pollster = "0.3"
rusqlite = { version = "0.31", features = ["bundled"] }
tungstenite = "0.21"
url = "2"
wgpu = "0.19"
winit = "0.29"
